### ISSUE TITLE
Add additional source for lyrics

### ISSUE THREAD

**Issue by GitGitro** [shub39/Rush#11]
please consider adding an additional source like spotify for those who get blocked by cloudflare on genius by the error 403 (captcha)

api reference: https://github.com/akashrchandran/spotify-lyrics-api

thank you!

**Comment by shub39** [comment]
I looked into this and it seems that adding an additional source for the lyrics will require a client id and secret thus, fdroid builds will not possible. However I could make it so that you share the song url from Spotify to rush and then it fetches the lyrics with the url. Will that be practical?

**Comment by GitGitro** [comment]
Uhm not really practical since i don't use spotify anymore.
But why the access token and id?
Maybe we could try like they did in [SongSync](https://github.com/Lambada10/SongSync) and even deploy your own instance on vercel, or i could deploy it for you myself with a burner account.
Alternatively there is another provider [LRCLib](https://github.com/Lambada10/SongSync/blob/master/app%2Fsrc%2Fmain%2Fjava%2Fpl%2Flambada%2Fsongsync%2Fdata%2Fremote%2Flyrics_providers%2Fothers%2FLRCLibAPI.kt) you could look into.
Let me know!

**Comment by shub39** [comment]
LrcLib is interesting. Thanks!

**Comment by shub39** [comment]
added lrclib
