### ISSUE TITLE
show lyrics meaning

### ISSUE THREAD

**Issue by chrostino** [shub39/Rush#12]
like on genius when you tap on some bars it shows the meaning, the app could pull this data from genius.
also I have a problem where the app keeps asking me permission to access notifications to auto search the song lyrics, but I don't want this feature, I'm ok manually searching

**Comment by shub39** [comment]
Since I am scraping the lyrics from genius, I doubt that it will be possible, will see the scraped data for details.

**Comment by shub39** [comment]
And will make notification permission a toggle in settings

**Comment by shub39** [comment]
so went through the scraped html and it seems they store the lyrics meaning as links...not as text. so getting lyrics meaning is very difficult and i dont think i will add it. you can always go to the genius page for that song from the genius icon.

**Comment by chrostino** [comment]
got it, so it's just the notification issue

**Comment by shub39** [comment]
done
