### ISSUE TITLE
Make automatic song search optional

### ISSUE THREAD

**Issue by Irgendeinwer** [shub39/Rush#13]
The automatic song search is pretty annoying if you don't want to search for the song you are currently listening to. Therefore it would be practical if an extra button got introduced near the one to search, that (and only that) automatically searches for the currently played song.

Thanks :)

**Comment by shub39** [comment]
Ohk then

**Comment by shub39** [comment]
how about a toggle in settings? adding another button is not good to look at.

**Comment by shub39** [comment]
check latest release
