### ISSUE TITLE
Lyrics with titles in Cyrillic are not loaded 

### ISSUE THREAD

**Issue by Debik5** [shub39/Rush#16]
Lyrics of songs whose titles contain Cyrillic are not loaded, but if the song title is in English, then the text in Cyrillic is loaded

Application version 1.4.0
Android 14

**Comment by shub39** [comment]
please share the search term. search results are provided by genius api so there is little i can do about it

**Comment by Debik5** [comment]
> please share the search term. search results are provided by genius api so there is little i can do about it

![Uploading Screenshot_20240723-014609_Rush.png…]()
![Uploading Screenshot_20240723-014601_Rush.png…]()
https://genius.com/Slava-marlow-ban-lyrics

**Comment by shub39** [comment]
the screenshots arent uploaded

**Comment by Debik5** [comment]
> the screenshots arent uploaded

Unfortunately, for some reason my screenshots are not attached, but the link I provided contains the lyrics of the song, which does not open. In Cyrillic the song is called "запретить" and appears first in the list.

**Comment by shub39** [comment]
![Screenshot_20240724_090500](https://github.com/user-attachments/assets/a5bafbaa-8979-4401-9d0a-58260c88a6ea)

they are loading?

**Comment by Debik5** [comment]
> ![Screenshot_20240724_090500](https://private-user-images.githubusercontent.com/143277026/351564748-a5bafbaa-8979-4401-9d0a-58260c88a6ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5ODI5MTYsIm5iZiI6MTcyMTk4MjYxNiwicGF0aCI6Ii8xNDMyNzcwMjYvMzUxNTY0NzQ4LWE1YmFmYmFhLTg5NzktNDQwMS05ZDBhLTU4MjYwYzg4YTZlYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNlQwODMwMTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMzdhM2UwYWM2ZTZjZWEzOWYzNTRhNzAyODJlMzE4MmI5MDk3MjQzNmZhZTcyNTUxNThlNjI4YTYwMjUwMzRjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.R3Ufo-T6FQXNOWkyilgZRw93KKS8brAjAUlu3kG8DMg)
> 
> they are loading?

The lyrics of the first song from the list in the screenshot do not load

**Comment by shub39** [comment]
the genius lyrics is not loading. will look into it. is the lrclib lyrics wrong or smth?

**Comment by shub39** [comment]
its fixed now. closing issue
