### ISSUE TITLE
Copying complete lyrics

### ISSUE THREAD

**Issue by thatspix** [shub39/Rush#17]
Heyo!

First off, thank you for this beautiful and simple app.

Can you add a feature/button that copies the entire lyric to clipboard?

I mostly listen to offline music and I keep their metadata up-to-date. So I add lyrics to the song by copying from Genius but the Genius app doesn't allow to select all the lyrics in a single click. Copying from a webpage doesn't maintain the spacing and formatting.

it would be a game changer if you can implement this.

**Comment by shub39** [comment]
Yeah, currently working on it

**Comment by thatspix** [comment]
> Yeah, currently working on it

Amazing, looking forward to it

**Comment by mokazemi** [comment]
Wow, thanks 🙏🏻 
Also copying the selected lines would be so beneficial.

**Comment by shub39** [comment]
Added on 1.5.0
