### ISSUE TITLE
Request to get Notification access for Auto Searching

### ISSUE THREAD

**Issue by 1bl4z3r** [shub39/Rush#2]
Hi @shub39 

A totally rad app. But now the search for lyrics is manual.

Is there a plan to get Notification access to get Spotify's current playing song and searching automatically?

**Comment by shub39** [comment]
Thanks!

Yeah that feature is planned. Currently figuring it out, hopefully it'd be out by next update

**Comment by 1bl4z3r** [comment]
Cool cool cool
Will be waiting for that.

Closing the Issue
