### ISSUE TITLE
feat: bring back open in genius button

### ISSUE THREAD

**Issue by xynydev** [shub39/Rush#20]
After the switch to Lrclib the app had a button with the Genius logo on it to open the song in Genius. Now that button just fetches the lyrics from Genius instead. (which I guess is an UX improvement) However, I'm interested in the annotations on Genius. I understand that fetching them into the app wouldn't be feasible, though.

Would it be possible to add back a button to open the song in Genius? As an optional settings toggle or in hidden in a menu is fine with me, I'm not sure where it would be most intuitive.

**Comment by shub39** [comment]
moved that button to the end of lyrics. Idk where else to put it as where it was taking too much space where it  was before

**Comment by xynydev** [comment]
Thanks, I see it now!
