### ISSUE TITLE
Importing musics's name and search automatically (Bulk)

### ISSUE THREAD

**Issue by AmIrbX** [shub39/Rush#23]
I really like the app as i love listening musics and sometimes i want to check the song's lyrics but i didn't want to buy a spotify premium for it.

I worked with Rush and it's good for me except that i have tons of musics that i want to have their lyrics and I'm kindda lazy to search each one of them so i think a bulk import/scan for musics and searching for their lyrics will be really nice and i know Rush is still at its first stages but i just wanted to make a suggestion.

Tnx guys.

**Comment by shub39** [comment]
Will look into it.

**Comment by shub39** [comment]
added on latest. check it out
