### ISSUE TITLE
Rename Image File Name to Include Artist and Song Name

### ISSUE THREAD

**Issue by codeiimon** [shub39/Rush#25]
Hello!

Just wanted to tell you first and foremost that I love this app. Its almost perfect for my use case but its missing something I would like.

Personally, I like to save the music quotes images from this app locally on device, so that I look through later (I use an app for this called [ShareToStorage](https://github.com/MateusRodCosta/Share2Storage) which saves shared images to the phone's local storage). I would also like to keep things organized, so its a bit unfortunate that images shared from this app are always named "shared_image.png". It means that I have to go within my phone's file manager and rename the image to something less forgettable.

It would be nice if they were named with the Artists Name and the Song name (ie: "_Artist Name_ - _Song Name_.jpg") rather than just "shared_image.png". It would be even better if we could choose a folder within the app to save these images to, so I don't have to use a third party app for this process.

**Comment by shub39** [comment]
Thanks! this can be done, will look into it

**Comment by shub39** [comment]
added this on 2.1.0, check it out

**Comment by codeiimon** [comment]
Yo thank you so much! Tried it out a few days and its fits my needs perfectly. Wishing you the best in all your future endeavors 🫡.
