### ISSUE TITLE
Making Rounded Edges' BG Transparent & Adding BG Customizability

### ISSUE THREAD

**Issue by shahriaar0** [shub39/Rush#28]
This app has far surpassed Spotify, so thank you for that. 
One issue I've faced is that when I use the rounded edges, there's a black background instead of it being transparent. 

As a future feature request, allowing the user to change the background's size (e.g. _for stories, covers_) with more colors/fonts would be superb. Keep up the good work.

**Comment by shub39** [comment]
Thanks!

the corners are transparent but some apps like instagram edit the image before sharing, working on a button to save the image to local storage first, that should fix it.
Working on a new card style and fonts are on the list!
