### ISSUE TITLE
lyrics page

### ISSUE THREAD

**Issue by rusty-man** [shub39/Rush#3]
If back gesture is done when song lyrics are open, it quits the app. Currently the only way i can find to go to home is to close the app and open it again.

Could you make it so that back gesture instead takes you to the home page of the app; and then quit the app from there?
Or atleast a button to return to home?

Thanks

**Comment by Irgendeinwer** [comment]
You can just swipe to the left to get to the home page. But still I think that the back gesture of the OS should take you to the home page too.

**Comment by rusty-man** [comment]
That's better than nothing. Thanks for sharing.

**Comment by shub39** [comment]
ok then will change it next update

**Comment by shub39** [comment]
the latest release should fix your issue

**Comment by rusty-man** [comment]
hasnt been fixed in 1.2.0

**Comment by rusty-man** [comment]
https://github.com/user-attachments/assets/19263dce-2e8c-4377-8342-4cf8c2e3e9ea

**Comment by shub39** [comment]
oh sorry man. thought this was a different issue. btw is the song title autofill working on your device?

**Comment by shub39** [comment]
Done!

**Comment by rusty-man** [comment]
autofill is sometimes working and sometimes not

i can't seem to figure out under what conditions it works / doesnt work
