### ISSUE TITLE
question on permissions

### ISSUE THREAD

**Issue by IzzySoft** [shub39/Rush#36]
Just having returned from vacation, I'm catching up with the backlog… The scanner at IzzyOnDroid reported 10 days or so ago:

```
! repo/com.shub39.rush_17.apk declares sensitive permission(s):
  android.permission.READ_EXTERNAL_STORAGE android.permission.READ_MEDIA_AUDIO
```

Could you please clarify what those are needed for? I cannot gather it from the changelogs. Thanks in advance!

**Comment by shub39** [comment]
its for importing lyrics for local files.

**Comment by shub39** [comment]
so looking into this, these permissions are not required. Guess i put them there while trying implementations and forgot to remove them. removing them right now

**Comment by IzzySoft** [comment]
Thanks! Guess for importing, SAF (and the FilePicker) will work then, right? Looking forward to the next release then to see what the scanner says then. Just wanted to say "no rush", but eh would that be ambiguous here :see_no_evil: So I rather write: at your pace. If you give me a ping once the new release is there, I'll check ASAP so we can close this issue.

**Comment by shub39** [comment]
@IzzySoft new release is out

**Comment by IzzySoft** [comment]
And already available at IoD, looking good – thanks! Closing up here then.

**Comment by IzzySoft** [comment]
On 2024-12-19, scanner reported `android.permission.READ_MEDIA_IMAGES` – was that intentionally added, or did it slip in, @shub39?

**Comment by shub39** [comment]
Yeah that's intentional for the new cards.

**Comment by IzzySoft** [comment]
Thanks! Could you clarify a little more? Like, is it for choosing images as backgrounds for new cards (would be my first guess, but not using your app myself I cannot be sure)?

**Comment by shub39** [comment]
Yes it's exactly that 😅

**Comment by IzzySoft** [comment]
Thanks! Added to the app's "green list" then :smiley:

**Comment by shub39** [comment]
Oh @bpavuk added code for audio visualizers and audio sensitive backgrounds in this update. They use the visualizer api which require this permission. It looks like this https://bsky.app/profile/shub39.bsky.social/post/3m24zsg4jxk2e

**Comment by bpavuk** [comment]
I concur. the Visualizer API does require an audio permission.

btw I need to make a smoother permission request flow. now, if you click on "Wave" or "Gradient," you are harshly met with the microphone requirement with zero explanations

**Comment by IzzySoft** [comment]
Thanks! That rings a bell, had that before somewhere. (and yes, that was the "vague idea" I couldn't name)
