### ISSUE TITLE
Android 10: Unable to Save lyrics to Pictures Directory

### ISSUE THREAD

**Issue by maivohun** [shub39/Rush#37]
![ResizedImage_2024-10-14_02-57-56_1458](https://github.com/user-attachments/assets/45d01512-9e9e-4f22-82cf-15b02087c74a)

Tapping "Save Changes" does nothing.

**Comment by shub39** [comment]
Is this the only song or nothing can be saved?

**Comment by maivohun** [comment]
I've been unable to save any songs I've tried so far, but the same songs save without issues when using Android 13 and 14.

**Comment by shub39** [comment]
Ohk will look into it. Kinda don't wanna fix things for a10 because it's old but ok

**Comment by maivohun** [comment]
I understand. Don't have to if it requires too much tinkering. In whicn case, I'd recommend you add a note about minimum android version to use this particular feature.

**Comment by shub39** [comment]
can you join the discord? released a beta apk there need to confirm if this issue is fixed

**Comment by maivohun** [comment]
Fix is working, but noticed some other things, please check Discord.
