### ISSUE TITLE
Search lyrics: Text remains after search

### ISSUE THREAD

**Issue by Irgendeinwer** [shub39/Rush#4]
After you have searched for a song, the search term remains and must first be deleted when searching again.

It would be great for the search field to reset after a song got added to the saved-list.

Thanks :smile: 

https://github.com/shub39/Rush/assets/175053643/a92d0237-5dad-4c3f-a0dd-ec89cf23b3ae

**Comment by Irgendeinwer** [comment]
In the new version (9) a delete button got introduced next to the text field. This makes it easier to delete the search term but it would still be faster to start with a new search every time.

**Comment by shub39** [comment]
alright
