### ISSUE TITLE
Notification permission (and auto-search) not working

### ISSUE THREAD

**Issue by ccrowles** [shub39/Rush#40]
Despite giving full permission to read notifications, it's not able to auto-search lyrics when Spotify is playing, and when I go check in the app's settings it shows that there are no permissions granted.

![Screenshot_20241015-110408_Settings](https://github.com/user-attachments/assets/1e593f21-cba3-433c-b815-d3a3a373edf2)

But as you can see the button is not there anymore because I _did_ give it permissions like it requested.
![Screenshot_20241015-110357_Rush](https://github.com/user-attachments/assets/145134e4-3b94-499d-9ae0-18eac7638e0f)

Phone model: ZenFone 9
Android version: 14

**Comment by shub39** [comment]
Yeah will look into it, right now a workaround is pausing and playing the song from notifications when in Rush. can you check if this is working for you?

**Comment by ccrowles** [comment]
Tried, I can confirm it works as a temporary workaround.

**Comment by ccrowles** [comment]
If you could send the beta here it would be great!
(I am in way too many discord servers and it's already kinda overwhelming as it is)

**Comment by shub39** [comment]
tried its not supported apparently 

trying the link
https://cdn.discordapp.com/attachments/1262033675034296350/1295778175380619346/app-beta.apk?ex=670fe2f7&is=670e9177&hm=91c18cc74b806e3e06c2af56dd4a8bcb3a14c510a666d24086ea669bdb505cef&

**Comment by ccrowles** [comment]
Yep, the link works and that apk solves the issue!

**Comment by shub39** [comment]
yay will close the issue on next release as im still not sure if this fix is the best approach

**Comment by ccrowles** [comment]
Ok, thanks again!
