### ISSUE TITLE
The numbers in "Maximum Lines to share" option are hidden

### ISSUE THREAD

**Issue by luxdev01** [shub39/Rush#54]
**Description**

I'm aware that it's because of the size of the string, but I don't know if it would be possible to resolve this in the `strings.xml`  file (pt-rBR) or It's a UI related issue.

**Screenshot**

![Screenshot_20241122-1710212024-11-22_17-26-38_5538.png](https://github.com/user-attachments/assets/1ce8b2f2-8d5d-4270-a106-08d799b6caef)

**Comment by shub39** [comment]
Oh this will be fixed in the next release
