### ISSUE TITLE
F-Droid build not reproducible

### ISSUE THREAD

**Issue by linsui** [shub39/Rush#6]
Can you clean the cache and rebuild the apk?

**Comment by shub39** [comment]
done on latest release

**Comment by linsui** [comment]
Thanks!

**Comment by linsui** [comment]
1.1.0 assets/dexopt/baseline.prof is not reproducible. Not sure why.

**Comment by shub39** [comment]
cleaned cache and rebuilt 1.2.0

**Comment by linsui** [comment]
It's fixed, thanks!

**Comment by licaon-kter** [comment]
and again https://monitor.f-droid.org/builds/log/com.shub39.rush/10#site-footer

**Comment by shub39** [comment]
cleaned caches and rebuilt from tag. Will building the app from github actions prevent this?

**Comment by linsui** [comment]
You just need to remember to clean cache before release. :) CI helps of course. It's fixed, thanks!

**Comment by licaon-kter** [comment]
do reopen, ref: https://gitlab.com/fdroid/fdroiddata/-/jobs/7580679226#L1159

difflog: [rush12.log](https://github.com/user-attachments/files/16614701/rush12.log)

**Comment by IzzySoft** [comment]
@shub39 confirm RB failure. That APK was not build from a clean tree at the commit the tag points to. It has the previous commit hash embedded – but even building at that it fails. So you've most likely built it from a dirty tree somewhere between the two commits.

Please take a look at our [hints on reproducible builds](https://gitlab.com/IzzyOnDroid/repo/-/wikis/Reproducible-Builds), and take special care for the "first basic rule" :wink: "Violating" that one is the most frequent cause of failing RBs.

**Comment by shub39** [comment]
Done, Sorry I totally forgot about that will make sure this never happens again. Thanks again for putting up with me 🫠

**Comment by IzzySoft** [comment]
Looking forward to the next release being RB again then – while LK will need to know which commit to build and which APK to match it on :wink:

**Comment by licaon-kter** [comment]
>  while LK

@IzzySoft ?

**Comment by IzzySoft** [comment]
@licaon-kter how do you know what commit to build and what APK to compare against? As you won't suggest to drop and recreate the release (we agreed that's a bad idea), the only other alternative would be to disable this release on your end. Or what did I miss?

**Comment by licaon-kter** [comment]
Will wait for 1.8.0, I see commits already bumped the version anyway
