### ISSUE TITLE
Auto search for lyrics doesn't work.

### ISSUE THREAD

**Issue by thethirdmanironman** [shub39/Rush#7]
I've enabled notification access but still, it doesn't work. Thank you for this app tho

**Comment by shub39** [comment]
Are you using android 11 or below?

**Comment by thethirdmanironman** [comment]
> Are you using android 11 or below?

Yes. 11

**Comment by shub39** [comment]
Sorry, currently it doesn't work below android 12 afaik. Working on a solution or maybe making notification access permission optional

**Comment by thethirdmanironman** [comment]
> Sorry, currently it doesn't work below android 12 afaik. Working on a solution or maybe making notification access permission optional

Can't you just implement this functionality the same way The "Fastlyrics" app implement it? It just work perfectly fine.

**Comment by shub39** [comment]
yeah will look into it, wanted to figure out something different than that implementation.

**Comment by thethirdmanironman** [comment]
> yeah will look into it, wanted to figure out something different than that implementation.

I appreciate the great UI and the excellent share lyrics functionality of your app. However, the only feature I find missing is auto lyrics detection. Implementing this would make the app even better.

**Comment by thethirdmanironman** [comment]
Updated the app, but still the same problem. Not solved

**Comment by Irgendeinwer** [comment]
> Updated the app, but still the same problem. Not solved

Did you try to reset the app data?

**Comment by thethirdmanironman** [comment]
> > Updated the app, but still the same problem. Not solved
> 
> Did you try to reset the app data?

Yeah I did, still the same issue

**Comment by shub39** [comment]
@thethirdmanironman huh. I tested in a11 virtual device and it was working. can you give me more details on device manufacturer, and which music apps you use?

**Comment by thethirdmanironman** [comment]
> @thethirdmanironman huh. I tested in a11 virtual device and it was working. can you give me more details on device manufacturer, and which music apps you use?

Xiaomi redmi note 8.
Spotify

And like I Said it work perfectly fine on "Fastlyrics" apo

**Comment by shub39** [comment]
can you try again by disabling battery optimisation for the app. miui tends to aggresively clear tasks and maybe its killing the notification listener...

**Comment by thethirdmanironman** [comment]
> can you try again by disabling battery optimisation for the app. miui tends to aggresively clear tasks and maybe its killing the notification listener... 

https://github.com/user-attachments/assets/8d0e01a2-784d-42db-a120-99bffac5b3e6

Still no luck.

**Comment by thethirdmanironman** [comment]
![IMG_20240714_154040.jpg](https://github.com/user-attachments/assets/e8bf1163-b165-43eb-bca3-25c0f6229bc5)

No restrictions

**Comment by shub39** [comment]
damn... actually i am having trouble implementing it like fastlyrics. really wanted this to work. could you join the discord so i can send test builds to you?

**Comment by thethirdmanironman** [comment]
> damn... actually i am having trouble implementing it like fastlyrics. really wanted this to work. could you join the discord so i can send test builds to you?

Yeah why not, I'll join.

**Comment by thethirdmanironman** [comment]
The link to the discord server?

**Comment by shub39** [comment]
in settings

**Comment by thethirdmanironman** [comment]
> in settings
> 

It doesn't work too 😅

**Comment by shub39** [comment]
wht? 💀 
https://discord.gg/yaxHyU66
you seriously should consider upgrading 😭
