### ISSUE TITLE
The layout is no longer full screen after update

### ISSUE THREAD

**Issue by bethropolis** [shub39/Rush#72]
![Screenshot_2024-12-22-05-31-47-35_4535071ea42a64a63676448e91cb0766.jpg](https://github.com/user-attachments/assets/8913cc03-0644-4da7-8397-6e655b44b70a)

I just updated to version 2.4.0 and now the app looks like it has a reduced viewport. 

device information:
android 14

**Comment by shub39** [comment]
yeah should have tested with different dpis, will be fixed or overhauled in the next update
